--ALTER USER 'orders_test'@'%' IDENTIFIED WITH mysql_native_password BY 'orders_test';--

CREATE TABLE events (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
message TEXT NOT NULL,
hash VARCHAR(32) NOT NULL,
event VARCHAR(20) NOT NULL,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE companies (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(32) NOT NULL,
identity VARCHAR(32) UNIQUE NOT NULL,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL
);